add zsh complete

diff --git a/v0 b/v0
--- a/v0
+++ b/v0
@@ -281,7 +281,11 @@ ___advise_main(){
         filepath="$tmp_filepath"
     fi
 
-    complete -F "___advise_completer" "$func"
+    if [ -z "$ZSH_VERSION" ];then
+        complete -F "___advise_completer" "$func"
+    else
+        compdef "___advise_completer" "$func"
+    fi
 }
 
 ___advise_update(){
@@ -298,7 +302,12 @@ ___advise_update(){
 ___advise_run(){
 
     local offset="${2:-0}"
-    local resname="${1:-${COMP_WORDS[0]}}"
+    local resname
+    if [ -n "$ZSH_VERSION" ];then
+        resname="${1:-${words[1]}}"
+    else
+        resname="${1:-${COMP_WORDS[0]}}"
+    fi
 
     if [ -z "$___ADVISE_RUN_CMD_FOLDER" ]; then
         ___ADVISE_RUN_CMD_FOLDER="${TMPDIR%/}/.x-cmd/advise_auto_json"
@@ -339,11 +348,17 @@ ___advise_run(){
 
         COMP_WORDS=("${words[@]}")
         COMP_CWORD="$(( ${#words[@]}-1 ))"
+
+    fi
+
+    if [ -n "$ZSH_VERSION" ];then
+        local COMP_WORDS=("${words[@]}")
+        local COMP_CWORD="$(( ${#words[@]}-1 ))"
     fi
 
     local cur="${COMP_WORDS[COMP_CWORD]}"
 
-    if [ "$cur" == "" ]; then
+    if [ "$cur" = "" ]; then
         # Notice: The following line handle zsh compatibility problem.
         # In zsh, When input word is empty, COMP_WORDS[COMP_CWORD] does not exist.
         # In bash, When input word is empty, COMP_WORDS[COMP_CWORD] exist, and it is ""
@@ -369,45 +384,51 @@ ___advise_run(){
     esac
 
     IFS=$'\n'   # Bash/Zsh Only
-
     [ -f "$filepath" ] || return
 
     local result
     result="$(
         {
             cat "$filepath"
-            printf "\034%s\034" "$s"  # printf "\034${s}\034"
+            printf "\034%s\034" "$s"
         } | awk -f "$___ADVISE_AWK_PATH" 2>/dev/null
     )"
-    IFS="$OLDIFS"
 
-    if [ -z "$ZSH_VERSION" ] && [[ "$BASH_VERSION" =~ /4.*/ ]];then
-        if [[ "$result" =~ [:=\/]$ ]];then
-            compopt -o nospace
-        else
-            compopt +o nospace
-        fi
-    fi
-
-    local cmd="${result##*#> }"
+    local cmd="${result##*\#> }"
     local cmd_result=""
     if [ "$cmd" != "$result" ]; then
         cmd_result="$(eval "$cmd" 2>/dev/null)"
-        result="${result%%#> *}"
+        result="${result%%\#> *}"
     fi
 
-    # shellcheck disable=SC2207
-    COMPREPLY=(
-        $(
-            compgen -W "$result
+
+    IFS="$OLDIFS"
+    # TODO:
+    if [ -n "$ZSH_VERSION" ];then
+        eval "result=($result)"
+        local commands=($result)
+        compadd -a commands
+    else
+        if [ -z "$ZSH_VERSION" ] && [[ "$BASH_VERSION" =~ /4.*/ ]];then
+            if [[ "$result" =~ [:=\/]$ ]];then
+                compopt -o nospace
+            else
+                compopt +o nospace
+            fi
+        fi
+
+        # shellcheck disable=SC2207
+        COMPREPLY=(
+            $(
+                compgen -W "$result
 $cmd_result" -- "$cur"
+            )
         )
-    )
 
-    __ltrim_completions "$cur" "@"
-    __ltrim_completions "$cur" ":"
-    __ltrim_completions "$cur" "="
-
+        __ltrim_completions "$cur" "@"
+        __ltrim_completions "$cur" ":"
+        __ltrim_completions "$cur" "="
+    fi
 }
 
 __ltrim_completions()
@@ -432,8 +453,9 @@ ___advise_completer() {
 
 # EndSection
 
-if [ -n "$ZSH_VERSION" ] && [ "$(autoload | grep bashcompinit)" = "" ]; then
-    autoload -U +X bashcompinit compinit && bashcompinit && compinit
+if [ -n "$ZSH_VERSION" ] && [ "$(autoload | grep compinit)" = "" ]; then
+    # autoload -U +X bashcompinit compinit && bashcompinit && compinit
+    autoload -Uz compinit && compinit
 fi
 
 advise init advise
@@ -477,13 +499,23 @@ ___advise_man_which(){
     return 1
 }
 
+# ___advise_man_load(){
+#     local cmd="${1:?Provide cmd}"
+#     local p="$(___advise_man_which "$cmd")"
+#     if [ ! -f "$p" ]; then
+#         printf "%s\n" "$cmd.json Not found. You could try 'advise man update' for updates." >&2
+#         return 1
+#     fi
+#     compgen "___advise_man_completer" "$cmd"
+# }
+
 ___advise_man_load(){
     local i
     for i in $(___advise_man_ls); do
-        if s=$(complete -p "${i%%/}" 1>/dev/null 2>&1); then
+        if s=$(complete -p "$i" 1>/dev/null 2>&1); then
             [[ "$s" == *___advise_completer* ]] && continue
         fi
-        complete -F "___advise_man_completer" "${i%%/}"
+        complete -F "___advise_man_completer" "$i"
     done
 }
 
@@ -503,11 +535,11 @@ ___advise_man_completer() {
 ___advise_man(){
     local op="${1:?Provide subcommand}"; shift
     case "$op" in
-        ls)         ___advise_man_ls              ;;
-        update)     ___advise_man_update          ;;
-        which)      ___advise_man_which "$@"      ;;
-        load)       ___advise_man_load            ;;
-        rm)         ___advise_man_rm              ;;
+        ls)         ___advise_man_ls ;;
+        update)     ___advise_man_update ;;
+        which)      ___advise_man_which "$@" ;;
+        load)       ___advise_man_load ;;
+        rm)         ___advise_man_rm ;;
         *)          ___advise_man_load "$op" "$@" ;;
     esac
 }
