update testcase template

diff --git a/dev/test/v0_test_awk b/dev/test/v0_test_awk
--- a/dev/test/v0_test_awk
+++ b/dev/test/v0_test_awk
@@ -1,9 +1,10 @@
 # shellcheck shell=bash
 
+xrc log advise xrc
+xrc assert
+
 test123(){
     local fp="./dev/test/test.json"
-    echo "-----"
-    echo "Before awk: $*"
     local IFS=$'\002' # IFS="$(printf "\002")"
 
     s="$*"
@@ -12,11 +13,15 @@ test123(){
         cat "$fp"
         printf "\034%s\034" "$s"  # printf "\034${s}\034"
     } | awk -f "./v0.awk" # 2>/dev/null
-
-    echo -e "-----\n"
 }
 
-time test123 @a
+test_at(){
+    assert_stdout "test123 @a" <<A
+@a1
+@a2
+@a3
+A
+}
 
 # time test123 "$dir/3.json" r
 # test123 test-data2.json work r
@@ -47,3 +52,14 @@ time test123 @a
 # time test123 "$dir/3.json" user create1 ""
 
 
+start_test() {
+    < "$1" awk '$0~/^test_[^\(]+\(\)/{ gsub(/\(\)\{/, "", $0); print $0 }' | while read -r line; do
+        echo "Testing Function: $line"
+        if ! eval "$line"; then
+            printf "\033[0;31m======= Fail at function: %s \033[0m" "$line" >&2
+            break
+        fi
+    done
+}
+
+start_test ./dev/test/v0_test_awk
