chore(advise): update
link #ljh

diff --git a/lib/main b/lib/main
--- a/lib/main
+++ b/lib/main
@@ -18,11 +18,14 @@ ___advise_main(){
         local filepath=$tmp_filepath
         if [ ! -f "$filepath" ]; then
             local content
-            content="$(X_CMD_ADVISE_FUNC_NAME=$func eval "$func" _x_cmd_advise_json 2>/dev/null)"
-            if [ $? = 126 ]; then
+            x:debug "Start gen advise for $func"
+            content="$(X_CMD_ADVISE_FUNC_NAME=$func "$func" _x_cmd_advise_json)"
+            x:debug "Finished gen advise for $func"
+            if [ $? -eq 0 ]; then
                 printf "%s" "$content" >"$filepath"
+                x:debug "Finished gen advise for $func"
             else
-                return 0
+                x:error "Failed gen advise $func : First, you need to ensure that there are corresponding functions in the subcmd you define. Second, there are _x_cmd_advise_json the case does not need to be defined if param is used. If not, it needs to be manually defined or param: void is used."
             fi
         fi
     else
