...

diff --git a/lib/man b/lib/man
--- a/lib/man
+++ b/lib/man
@@ -29,6 +29,9 @@ ___x_cmd_advise_completion_update(){
         mkdir -p "$___X_CMD_ADVISE_MAN_COMPLETIONS_FOLDER/$___X_CMD_CUR_SHELL-completions"
         x uz "$CACHE_COMPLETIONS" "$___X_CMD_ADVISE_MAN_COMPLETIONS_FOLDER/$___X_CMD_CUR_SHELL-completions" >/dev/null
         x rmrf "$CACHE_COMPLETIONS" 1>/dev/null 2>&1
+    else
+        x:log "Fail to update $___X_CMD_CUR_SHELL-completion.7z from x-cmd/advise."
+        return 1
     fi
 }
 
@@ -39,25 +42,24 @@ ___x_cmd_advise_man_update(){
         mkdir -p "$___X_CMD_ADVISE_MAN_SRC_FOLDER"
         x uz "$CACHE" "$___X_CMD_ADVISE_MAN_SRC_FOLDER" >/dev/null
         x rmrf "$CACHE" 1>/dev/null 2>&1
+    else
+        x:log "Fail to update from x-cmd/advise."
+        return 1
     fi
 }
 
 ___x_cmd_advise_man_ls(){
-    if ___x_cmd_advise_man_exists || ___x_cmd_advise_man_update; then
-        local line
-        ls "$___X_CMD_ADVISE_MAN_SRC_FOLDER/$*" | while read -r line; do
-            [ "$line" = "LICENSE" ] || printf "%s\n" "$line"
-        done
-    fi
+    ___x_cmd_advise_man_exists || ___x_cmd_advise_man_update || return
+    local line
+    ls "$___X_CMD_ADVISE_MAN_SRC_FOLDER/$*" | while read -r line; do
+        [ "$line" = "LICENSE" ] || printf "%s\n" "$line"
+    done
 }
 
 ___x_cmd_advise_man_which(){
     local name="${1:?Provide name}"
 
-    ___x_cmd_advise_man_exists || ___x_cmd_advise_man_update || {
-        x:log "Advise update fails."
-        return 1
-    }
+    ___x_cmd_advise_man_exists || ___x_cmd_advise_man_update || return
 
     local file; while read -r file; do
         file="$___X_CMD_ADVISE_MAN_SRC_FOLDER/$file"
@@ -71,18 +73,23 @@ A
 
 }
 
-___x_cmd_advise_man_load(){
-
-    if [[ ! "${1:-""}" == "" ]]; then
-        if [ -z "$ZSH_VERSION" ];then
-            if [[ ! "$BASH_VERSION" =~ (^3.*|^4.[0-3]) ]]; then
-                complete -o nosort -F "___x_cmd_advise_man_completer" "$1" && return 1
-            else
-                complete -F "___x_cmd_advise_man_completer" "$1" && return 1
-            fi
+___x_cmd_advise_man_load_one(){
+    while [ "$#" -ge 1 ]; do
+        if [ -n "$ZSH_VERSION" ];then
+            compdef "___x_cmd_advise_man_completer" "$1"
+        elif [[ ! "$BASH_VERSION" =~ (^3.*|^4.[0-3]) ]]; then
+            complete -o nosort -F "___x_cmd_advise_man_completer" "$1"
         else
-            compdef "___x_cmd_advise_man_completer" "$1" && return 1
+            complete -F "___x_cmd_advise_man_completer" "$1"
         fi
+        shift
+    done
+}
+
+___x_cmd_advise_man_load(){
+    if [ "$#" -ge 1 ]; then
+        ___x_cmd_advise_man_load_one "$@"
+        return
     fi
 
     if ___x_cmd_advise_completions_exists || ___x_cmd_advise_completion_update; then
@@ -92,6 +99,7 @@ ___x_cmd_advise_man_load(){
             .  "$filename"
         fi
     fi
+
     local i; for i in $(___x_cmd_advise_man_ls); do
         if [ -z "$ZSH_VERSION" ];then
             [[ ! $(complete -p "$i" 2>/dev/null) == *___x_cmd_advise_man_completer* ]] || continue
