...

diff --git a/lib/man b/lib/man
--- a/lib/man
+++ b/lib/man
@@ -53,14 +53,22 @@ ___x_cmd_advise_man_ls(){
 
 ___x_cmd_advise_man_which(){
     local name="${1:?Provide name}"
-    local file
-    if ___x_cmd_advise_man_exists || ___x_cmd_advise_man_update; then
-        [ -f "$file" ] || file="$___X_CMD_ADVISE_MAN_SRC_FOLDER/$name/advise.t.json"
-        [ -f "$file" ] || file="$___X_CMD_ADVISE_MAN_SRC_FOLDER/npx/_/$name/advise.t.json"
-        [ -f "$file" ] || file="$___X_CMD_ADVISE_MAN_SRC_FOLDER/pipx/_/$name/advise.t.json"
-        [ -f "$file" ] || return 1
+
+    ___x_cmd_advise_man_exists || ___x_cmd_advise_man_update || {
+        x:log "Advise update fails."
+        return 1
+    }
+
+    local file; while read -r file; do
+        file="$___X_CMD_ADVISE_MAN_SRC_FOLDER/$file"
+        [ -f "$file" ] || continue
         printf "%s\n" "$file"
-    fi
+    done <<A
+$name/advise.t.json
+npx/_/$name/advise.t.json
+pipx/_/$name/advise.t.json
+A
+
 }
 
 ___x_cmd_advise_man_load(){
